services:
  redis:
    image: redis:latest
    container_name: bsimvis_redis
    ports:
      - "6379:6379"
    restart: always

  kvrocks:
    image: apache/kvrocks:2.15.0
    container_name: bsimvis_kvrocks
    # 1. Run as root to bypass the PID/Log permission issues on your laptop
    user: "0:0"
    ports:
      - "6666:6666"
    volumes:
      - ./kvrocks_data:/var/lib/kvrocks
      - ./kvrocks.conf:/var/lib/kvrocks/kvrocks.conf:ro
    # 2. Force the config and log to stdout
    entrypoint: [ "kvrocks", "-c", "/var/lib/kvrocks/kvrocks.conf", "--pidfile", "-1", "--log-dir", "stdout" ]
    deploy:
      resources:
        limits:
          memory: 20G
