bind 0.0.0.0
port 6666
# Point this to the base of your volume mount
# Overridden by --dir in launch.sh
# dir ./data/kvrocks
db-name db
log-dir stdout

# Allow large JSON uploads (2GB)
proto-max-bulk-len 2147483648

# 2GB RAM limits
rocksdb.block_cache_size 512
rocksdb.write_buffer_size 64
rocksdb.max_write_buffer_number 4
rocksdb.max_background_jobs 4
rocksdb.compression snappy