bind 0.0.0.0
port 6666
# Point this to the base of your volume mount
dir /var/lib/kvrocks
db-name db
log-dir stdout

# 2GB RAM limits
rocksdb.block_cache_size 512
rocksdb.write_buffer_size 64
rocksdb.max_write_buffer_number 4
rocksdb.max_background_jobs 4