"""Plain libc/libgcc symbol names, gated in boilerplate_tag_service.

Mined from FID-tagged and libc.a-matching names seen across collections.
"""

# fmt: off
GLIBC_PLAIN_NAMES = frozenset((
    "VP8Delete", "_Exit", "_Fork", "___asprintf_chk", "___fprintf_chk",
    "___pthread_cond_clockwait64", "___pthread_cond_timedwait64",
    "___pthread_unwind_next", "___sprintf_chk", "__abort_lock_rdlock",
    "__abort_lock_wrlock", "__add_to_environ", "__adddf3", "__addsf3",
    "__alloc_dir", "__asprintf_chk", "__atomic_wide_counter_load_relaxed",
    "__chk_fail", "__clone", "__clone3", "__clone3_internal", "__clone_internal",
    "__clone_internal_fallback", "__clone_pidfd_supported", "__close_nameservers",
    "__close_nocancel", "__closefrom_fallback", "__cmsg_nxthdr",
    "__condvar_cancel_waiting", "__condvar_cleanup_waiting",
    "__correctly_grouped_prefixmb", "__ctype_b_loc", "__ctype_init",
    "__ctype_tolower_loc", "__ctype_toupper_loc", "__current_locale_name",
    "__dcigettext", "__divdi3", "__dl_libc_freemem", "__dlmopen", "__dlopen",
    "__dlsym", "__dlvsym", "__drand48_iterate", "__eqdf2", "__errno_location",
    "__execvpex", "__fcntl64_nocancel", "__fcntl64_nocancel_adjusted",
    "__file_change_detection_for_fp", "__file_change_detection_for_path",
    "__file_change_detection_for_stat", "__file_is_unchanged", "__fixdfsi",
    "__floatsidf", "__fopen_internal", "__fopen_maybe_mmap", "__fortify_fail",
    "__fstat64_time64", "__fxprintf", "__fxprintf_nocancel", "__get_child_max",
    "__get_errlist", "__get_errname", "__get_nprocs_sched", "__getclktck",
    "__getdents", "__getdents64", "__gettext_extract_plural", "__gettext_free_exp",
    "__gettextparse", "__glibc_morecore", "__grouping_iterator_init",
    "__grouping_iterator_init_none", "__grouping_iterator_next",
    "__h_errno_location", "__handle_registered_modifier_mb",
    "__handle_registered_modifier_wc", "__hash_string", "__ifreq",
    "__inet6_scopeid_pton", "__inet_aton_exact", "__inet_pton_length",
    "__init_misc", "__init_sched_fifo_prio", "__internal_atexit", "__intl_freemem",
    "__longjmp", "__mbsrtowcs_l", "__memchr_generic", "__memcpy_chk",
    "__memcpy_generic", "__memcpy_sve", "__memmove_chk", "__memmove_generic",
    "__memmove_oryon1", "__memmove_sve", "__memset_kunpeng", "__mktime_internal",
    "__nanosleep64", "__nanosleep_time64", "__netlink_assert_response",
    "__netlink_close", "__netlink_free_handle", "__netlink_open",
    "__netlink_request", "__netlink_sendreq", "__new_exitfn",
    "__ns_name_length_uncompressed", "__ns_rr_cursor_init", "__ns_rr_cursor_next",
    "__ns_samebinaryname", "__nscd_cache_search", "__nscd_get_map_ref",
    "__nscd_get_mapping", "__nscd_get_nl_timestamp", "__nscd_gethostbyaddr_r",
    "__nscd_gethostbyname2_r", "__nscd_gethostbyname_r", "__nscd_hst_map_freemem",
    "__nscd_open_socket", "__nscd_unmap", "__nss_action_allocate",
    "__nss_action_freeres", "__nss_action_parse", "__nss_configure_lookup",
    "__nss_database_fork_prepare_parent", "__nss_database_fork_subprocess",
    "__nss_database_freeres", "__nss_database_get", "__nss_database_get_noreload",
    "__nss_dns_functions", "__nss_fgetent_r", "__nss_files_data_endent",
    "__nss_files_data_open", "__nss_files_data_put", "__nss_files_data_setent",
    "__nss_files_fopen", "__nss_files_functions", "__nss_hash",
    "__nss_hostname_digits_dots", "__nss_hostname_digits_dots_context",
    "__nss_hosts_lookup2", "__nss_lookup", "__nss_lookup_function",
    "__nss_module_allocate", "__nss_module_disable_loading", "__nss_module_freeres",
    "__nss_module_get_function", "__nss_module_load", "__nss_next2",
    "__nss_parse_line_result", "__nss_readline", "__nss_readline_seek", "__offtime",
    "__open64_nocancel", "__open_nocancel", "__openat_nocancel", "__opendirat",
    "__opensock", "__overflow", "__parse_one_specmb", "__parse_one_specwc",
    "__parsegrent", "__parsepwent", "__pgsreader",
    "__posix_spawn_file_actions_realloc", "__pread64_nocancel", "__read_nocancel",
    "__readall", "__readonly_area", "__readvall", "__register_atfork",
    "__res_binary_hnok", "__res_context_hostalias", "__res_context_mkquery",
    "__res_context_query", "__res_context_querydomain", "__res_context_search",
    "__res_context_send", "__res_enable_icmp", "__res_get_nsaddr",
    "__res_handle_no_aaaa", "__res_iclose", "__res_init", "__res_nclose",
    "__res_ninit", "__res_nopt", "__res_randomid", "__res_thread_freeres",
    "__res_vinit", "__resolv_conf_allocate", "__resolv_conf_attach",
    "__resolv_conf_detach", "__resolv_conf_get", "__resolv_conf_get_current",
    "__resolv_conf_load", "__resolv_conf_put", "__resolv_context_freeres",
    "__resolv_context_get", "__resolv_context_get_override",
    "__resolv_context_get_preinit", "__resolv_context_put", "__rtld_static_init",
    "__run_exit_handlers", "__run_postfork_handlers", "__run_prefork_handlers",
    "__sched_cpucount", "__set_thread_area", "__set_vma_name", "__shlim",
    "__sigjmp_save", "__sigsetjmp", "__spawn_valid_fd", "__spawni",
    "__spawni_child", "__spawnix", "__sprintf_chk", "__strerror_l",
    "__strftime_internal", "__strlen_asimd", "__strlen_generic",
    "__thread_gscope_wait", "__timedwait", "__tls_init_tp", "__tls_pre_init_tp",
    "__toread", "__towrite", "__translated_number_width", "__truncdfsf2",
    "__tz_compute", "__tz_convert", "__tzfile_compute", "__tzfile_default",
    "__tzfile_read", "__tzset_parse_tz", "__tzstring", "__tzstring_len",
    "__udivdi3", "__uflow", "__underflow", "__unlock", "__unlockfile", "__unorddf2",
    "__unregister_atfork", "__vasprintf_internal", "__vfwprintf_internal",
    "__vfxprintf", "__vsnprintf_internal", "__vsprintf_internal",
    "__wcrtomb_internal", "__woverflow", "__write_nocancel", "__wuflow",
    "__wunderflow", "_bfd_elf_strtab_free", "_dlerror_run", "_exit", "_fitoa_word",
    "_flushlbf", "_fpmaxtostr", "_itoa_word", "_longjmp_unwind",
    "_nss_dns_getcanonname_r", "_nss_dns_gethostbyaddr2_r",
    "_nss_dns_gethostbyaddr_r", "_nss_dns_gethostbyname2_r",
    "_nss_dns_gethostbyname3_r", "_nss_dns_gethostbyname4_r",
    "_nss_dns_gethostbyname_r", "_nss_dns_getnetbyaddr_r",
    "_nss_dns_getnetbyname_r", "_nss_files_endaliasent", "_nss_files_endetherent",
    "_nss_files_endgrent", "_nss_files_endhostent", "_nss_files_endnetent",
    "_nss_files_endnetgrent", "_nss_files_endprotoent", "_nss_files_endpwent",
    "_nss_files_endrpcent", "_nss_files_endservent", "_nss_files_endsgent",
    "_nss_files_endspent", "_nss_files_getaliasbyname_r",
    "_nss_files_getaliasent_r", "_nss_files_getetherent_r", "_nss_files_getgrent_r",
    "_nss_files_getgrgid_r", "_nss_files_getgrnam_r", "_nss_files_gethostbyaddr_r",
    "_nss_files_gethostbyname2_r", "_nss_files_gethostbyname3_r",
    "_nss_files_gethostbyname4_r", "_nss_files_gethostbyname_r",
    "_nss_files_gethostent_r", "_nss_files_gethostton_r",
    "_nss_files_getnetbyaddr_r", "_nss_files_getnetbyname_r",
    "_nss_files_getnetent_r", "_nss_files_getnetgrent_r", "_nss_files_getntohost_r",
    "_nss_files_getprotobyname_r", "_nss_files_getprotobynumber_r",
    "_nss_files_getprotoent_r", "_nss_files_getpwent_r", "_nss_files_getpwnam_r",
    "_nss_files_getpwuid_r", "_nss_files_getrpcbyname_r",
    "_nss_files_getrpcbynumber_r", "_nss_files_getrpcent_r",
    "_nss_files_getservbyname_r", "_nss_files_getservbyport_r",
    "_nss_files_getservent_r", "_nss_files_getsgent_r", "_nss_files_getsgnam_r",
    "_nss_files_getspent_r", "_nss_files_getspnam_r", "_nss_files_initgroups_dyn",
    "_nss_files_parse_etherent", "_nss_files_parse_grent",
    "_nss_files_parse_netent", "_nss_files_parse_protoent",
    "_nss_files_parse_pwent", "_nss_files_parse_rpcent", "_nss_files_parse_servent",
    "_nss_files_parse_sgent", "_nss_files_parse_spent", "_nss_files_setaliasent",
    "_nss_files_setetherent", "_nss_files_setgrent", "_nss_files_sethostent",
    "_nss_files_setnetent", "_nss_files_setnetgrent", "_nss_files_setprotoent",
    "_nss_files_setpwent", "_nss_files_setrpcent", "_nss_files_setservent",
    "_nss_files_setsgent", "_nss_files_setspent", "_nss_netgroup_parseline",
    "_pthread_cleanup_pop", "_pthread_cleanup_pop_restore", "_pthread_cleanup_push",
    "_res_hconf_init", "_res_hconf_reorder_addrs", "_res_hconf_trim_domain",
    "_res_hconf_trim_domains", "_setjmp", "abort", "accept", "access",
    "action_list_add__", "add_alias2", "add_module", "add_name_to_object",
    "add_path", "add_to_global_resize", "add_to_global_resize_failure",
    "add_to_global_update", "adjust_wide_data", "alias_compare", "aligned_alloc",
    "alloc_new_heap", "alloc_perturb", "arena_get2", "arena_get_retry", "arg_bool",
    "arg_trimdomain_list", "argz_add_sep", "argz_create_sep", "asprintf", "atexit",
    "atoi", "base_of_encoded_value", "bcmp", "bcopy", "bind", "bindresvport", "brk",
    "bsd_signal", "btowc", "bzero", "cache_rpath", "call_dl_init", "call_dl_lookup",
    "call_fini", "call_init", "call_weak_fn", "calloc", "cancel_handler",
    "char_buffer_add_slow", "chdir", "check_match", "check_one_fd", "chmod",
    "clear_once_control", "clearenv", "clock", "clock_getres", "clock_gettime",
    "clock_nanosleep", "clone", "close", "close_file", "closedir", "compute_change",
    "connect", "context_reuse", "creat", "create_thread", "dcgettext",
    "decide_maybe_mmap", "decompose_rpath", "derivation_compare", "detach_arena",
    "dfs_traversal", "dl_open_worker", "dl_open_worker_begin", "dladdr", "dladdr1",
    "dlclose", "dlerror", "dlerror_run", "dlinfo", "dlinfo_doit", "dlmopen",
    "dlmopen_doit", "dlopen", "dlopen_doit", "dlsym", "dlsym_doit", "dlvsym",
    "dlvsym_doit", "dn_expand", "dn_skipname", "do_dlclose", "do_dlopen",
    "do_dlsym", "do_dlsym_private", "do_dlvsym", "do_init", "do_lookup_x",
    "do_release_all", "do_release_shlib", "do_swap", "do_sym", "do_system",
    "do_tunable_update_val", "dup2", "endmntent", "endservent", "enlarge_userbuf",
    "epoll_create", "epoll_ctl", "epoll_wait", "execl", "execve", "execvp",
    "execvpe", "exit", "expand_dynamic_string_token", "fatal_error", "fchdir",
    "fclose", "fcntl", "fcntl64", "fdopen", "fdopendir", "fflush_unlocked", "ffs",
    "fgetc", "fgetc_unlocked", "fgetgrent_r", "fgetpos", "fgetpwent_r", "fgets",
    "fgets_unlocked", "fileno", "fillin_rpath", "find_derivation", "find_module",
    "find_module_idx", "flock", "flush_cleanup", "fopen", "fopen64", "fork",
    "fprintf", "fputc", "fputs", "fputs_unlocked", "fread", "fread_unlocked",
    "free", "free_category", "free_derivation", "free_modules_db", "free_slotinfo",
    "freeaddrinfo", "frexp", "frexpl", "fscanf", "fseek", "fseeko", "fseeko64",
    "fsetpos", "fstat", "fstat64", "fstatat64", "fsync", "ftello", "ftello64",
    "funlockfile", "fwrite", "fwrite_unlocked", "gconv_parse_code",
    "get_avphys_pages", "get_eit_entry", "get_locked_global", "get_next_alias",
    "get_nproc_stat", "get_nprocs", "get_nprocs_conf", "get_phys_pages",
    "getaddrinfo", "getanswer_r", "getanswer_r_store_alias", "getc",
    "getc_unlocked", "getcwd", "getdelim", "getdents64", "getdtablesize", "getegid",
    "getenv", "geteuid", "getgid", "gethostbyaddr_r", "gethostbyname",
    "gethostbyname2", "gethostbyname2_r", "gethostbyname3_context",
    "gethostbyname3_multi", "gethostbyname_r", "gethostname", "getifaddrs",
    "getifaddrs_internal", "getline", "getloadavg", "getmntent", "getmntent_r",
    "getpagesize", "getpeername", "getpgid", "getpgrp", "getpid", "getppid",
    "getrandom", "getrlimit", "getrlimit64", "getservbyname_r", "getservbyport_r",
    "getservent_r", "getsid", "getsockname", "getsockopt", "gettid", "gettimeofday",
    "getuid", "global_state_allocate", "group_number", "gsignal", "hack_digit",
    "htonl", "htons", "if_freenameindex", "if_indextoname", "if_nameindex",
    "if_nametoindex", "index", "indirect_msort_with_tmp", "inet_addr", "inet_aton",
    "inet_aton_end", "inet_makeaddr", "inet_network", "inet_ntoa", "inet_ntop",
    "inet_pton", "inet_pton4", "init", "initstate", "initstate_r",
    "inotify_add_watch", "inotify_init", "insert_module", "int_mallinfo", "ioctl",
    "is_dst", "is_trusted_path_normalize", "isatty", "isspace", "kill", "killpg",
    "known_compare", "lame_encode_finish", "length_mismatch", "listen",
    "localeconv", "localtime", "localtime_r", "locked_vfxprintf", "longjmp",
    "lrand48_r", "lseek", "lseek64", "lstat64", "madvise", "mallinfo", "mallinfo2",
    "malloc", "malloc_consolidate", "malloc_info", "malloc_printerr",
    "malloc_stats", "malloc_trim", "malloc_usable_size", "mallopt",
    "maybe_split_for_insert", "mbrlen", "mbrtowc", "mbsnrtowcs", "mbsrtowcs",
    "memalign", "memchr", "memcmp", "memcpy", "memmem", "memmove", "mempcpy",
    "memrchr", "memset", "mkdir", "mmap", "mmap64", "mmap_remap_check",
    "module_load", "module_load_builtin", "mprotect", "mremap", "msort_with_tmp",
    "msync", "munmap", "munmap_chunk", "name_to_database_index",
    "nameserver_list_emplace", "nanosleep", "new_composite_name", "new_do_write",
    "new_heap", "next_line", "next_unwind_byte", "nrand48_r", "ns_name_compress",
    "ns_name_ntop", "ns_name_pack", "ns_name_pton", "ns_name_skip",
    "ns_name_uncompress", "ns_name_unpack", "nscd_gethst_r",
    "nss_database_check_reload_and_get", "nss_files_global_allocate", "ntohl",
    "ntohs", "on_exit", "open", "open64", "open_path", "open_socket", "open_verify",
    "openat64", "openaux", "opendir", "opendir_tail",
    "outstring_converted_wide_string", "parse_lsda_header", "parse_offset",
    "parse_rule", "parse_tzname", "pause", "pclose", "perror", "pipe", "pipe2",
    "plural_eval", "poll", "popen", "posix_memalign", "posix_spawn",
    "posix_spawn_file_actions_addclose", "posix_spawn_file_actions_adddup2",
    "posix_spawn_file_actions_destroy", "posix_spawn_file_actions_init",
    "posix_spawnattr_init", "posix_spawnattr_setflags",
    "posix_spawnattr_setsigdefault", "posix_spawnattr_setsigmask", "prctl", "pread",
    "pread64", "printf", "printf_positional", "pthread_atfork",
    "pthread_attr_destroy", "pthread_attr_getdetachstate",
    "pthread_attr_getguardsize", "pthread_attr_getinheritsched",
    "pthread_attr_getschedparam", "pthread_attr_getschedpolicy",
    "pthread_attr_getscope", "pthread_attr_getstackaddr",
    "pthread_attr_getstacksize", "pthread_attr_init", "pthread_attr_setaffinity_np",
    "pthread_attr_setdetachstate", "pthread_attr_setguardsize",
    "pthread_attr_setinheritsched", "pthread_attr_setschedparam",
    "pthread_attr_setschedpolicy", "pthread_attr_setscope",
    "pthread_attr_setstackaddr", "pthread_attr_setstacksize", "pthread_cancel",
    "pthread_cond_broadcast", "pthread_cond_clockwait", "pthread_cond_destroy",
    "pthread_cond_init", "pthread_cond_signal", "pthread_cond_timedwait",
    "pthread_cond_wait", "pthread_condattr_destroy", "pthread_condattr_getpshared",
    "pthread_condattr_init", "pthread_condattr_setpshared", "pthread_create",
    "pthread_detach", "pthread_equal", "pthread_exit", "pthread_getattr_default_np",
    "pthread_getconcurrency", "pthread_getschedparam", "pthread_getspecific",
    "pthread_join", "pthread_key_create", "pthread_key_delete", "pthread_kill",
    "pthread_mutex_destroy", "pthread_mutex_init", "pthread_mutex_lock",
    "pthread_mutex_timedlock", "pthread_mutex_trylock", "pthread_mutex_unlock",
    "pthread_mutexattr_destroy", "pthread_mutexattr_getpshared",
    "pthread_mutexattr_init", "pthread_mutexattr_setpshared",
    "pthread_mutexattr_settype", "pthread_once", "pthread_rwlock_init",
    "pthread_rwlock_rdlock", "pthread_rwlock_trywrlock", "pthread_rwlock_unlock",
    "pthread_rwlock_wrlock", "pthread_self", "pthread_setcancelstate",
    "pthread_setcanceltype", "pthread_setconcurrency", "pthread_setschedparam",
    "pthread_setspecific", "pthread_sigmask", "pthread_testcancel", "ptmalloc_init",
    "ptrace", "putc_unlocked", "puts", "pvalloc", "pwrite", "pwrite64", "qsort",
    "qsort_r", "raise", "rand", "random", "random_r", "rangecmp", "ranged_convert",
    "rawmemchr", "read", "read_alias_file", "read_conf_file", "read_encoded_value",
    "read_encoded_value_with_base", "read_sleb128", "read_sysfs_file",
    "read_uleb128", "readdir", "readdir64", "readlink", "readv", "realloc",
    "realpath", "recv", "recvfrom", "recvmsg", "register_printf_function",
    "register_printf_modifier", "register_printf_specifier", "register_printf_type",
    "relocate_pc24", "remove", "remove_slotinfo", "rename", "reopen", "res_dnok",
    "res_hnok", "res_mailok", "res_mkquery", "res_nmkquery", "res_nquery",
    "res_nquerydomain", "res_nsearch", "res_nsend", "res_ownok", "res_query",
    "res_querydomain", "res_search", "res_send", "res_setoptions",
    "resolv_conf_matches", "restore_core_regs", "restore_non_core_regs", "rewind",
    "rewinddir", "rindex", "rmdir", "round_and_return", "round_away",
    "save_for_backup", "save_for_wbackup", "sbrk", "sccp", "sched_get_priority_max",
    "sched_get_priority_min", "sched_getaffinity", "sched_getparam",
    "sched_getscheduler", "sched_setaffinity", "sched_setparam",
    "sched_setscheduler", "sched_yield", "search_EIT_table", "search_cache",
    "seekdir", "select", "selfrel_offset31", "sem_close", "sem_destroy",
    "sem_getvalue", "sem_init", "sem_open", "sem_post", "sem_timedwait",
    "sem_trywait", "sem_unlink", "sem_wait", "send", "send_vc", "sendmmsg",
    "sendmsg", "sendto", "setenv", "setgid", "setjmp", "setlocale", "setpgid",
    "setrlimit", "setrlimit64", "setservent", "setsid", "setsockopt", "setstate",
    "setstate_r", "setuid", "sgetsgent_r", "sgetspent_r", "shutdown", "sigaction",
    "sigaddset", "sigcancel_handler", "sigdelset", "sigemptyset", "sigfillset",
    "sigismember", "siglongjmp", "signal", "sigprocmask", "sigsuspend", "sigwait",
    "skip_and_NUL_space", "skip_nospace", "sleep", "snprintf", "sock_eq", "socket",
    "socketpair", "sprintf", "srand", "srand48_r", "srandom", "srandom_r", "sscanf",
    "start_thread", "stat", "stat64", "statfs64", "stpcpy", "str_to_mpn",
    "strcasecmp", "strcasecmp_l", "strcasestr", "strcat", "strchr", "strchrnul",
    "strcmp", "strcoll", "strcpy", "strcspn", "strdup", "strerror", "strerror_r",
    "strftime", "strftime_l", "strlen", "strncasecmp", "strncasecmp_l", "strncat",
    "strncmp", "strncpy", "strndup", "strnlen", "strpbrk", "strrchr", "strsep",
    "strspn", "strstr", "strtof", "strtof32x", "strtof64_l", "strtof_l", "strtok",
    "strtok_r", "strtol", "strtol_l", "strtold", "strtold_l", "strtoll_l", "strtoq",
    "strtoul", "strtoul_l", "strtoull_l", "strtouq", "sync", "syscall", "sysconf",
    "sysinfo", "sysmalloc", "sysmalloc_mmap", "sysmalloc_mmap_fallback", "system",
    "systrim", "tcache_double_free_verify", "tcache_init", "tcdrain", "tcgetattr",
    "tcsetattr", "tcsetpgrp", "tdelete", "tdestroy", "tdestroy_recurse", "tfind",
    "time", "timelocal", "times", "tolower", "toupper", "towctrans", "transcmp",
    "trecurse", "trecurse_r", "tsearch", "tunable_initialize", "twalk", "twalk_r",
    "two_way_long_needle", "tzset", "tzset_internal", "umask", "uname", "ungetc",
    "unlink", "unlink_chunk", "unlock", "unsetenv", "unwind_cleanup",
    "unwind_phase2", "unwind_phase2_forced", "unwind_stop", "usleep", "valloc",
    "vasprintf", "vfork", "vfprintf", "vfscanf", "vsnprintf", "vsprintf", "vsscanf",
    "wait", "wait4", "wait_on_socket", "waitid", "waitpid", "wcrtomb", "wcschr",
    "wcschrnul", "wcslen", "wcsnlen", "wcsnrtombs", "wcsrtombs", "wctomb",
    "wctrans", "wmemchr", "wmemcpy", "wmemmove", "wmempcpy", "wmemset", "write",
    "writev",
    "_itoa", "_fitoa", "_itowa", "_mid_memalign", "_exit", "_vfprintf_internal", "_wordcopy_fwd_dest_aligned", "_wordcopy_bwd_dest_aligned", "_wordcopy_fwd_aligned", "_wordcopy_bwd_aligned", "_authenticate", "_seterr_reply", "_rpc_dtablesize", "_create_xid", "_fpreset", "_do_one_spec", "_is_equal_or_bigger_arg", "_setargv", "_fpmaxtostr", "_locale_set_l", "_locale_init_l", "_locale_init", "_wchar_utf8sntowcs", "_wchar_wcsntoutf8s", "_restgpr_31_x", "_FINI_0", "_FINI_1", "_ValidateImageBase", "_FindPESection", "_FindPESectionByName", "_FindPESectionExec", "_GetPEImageBase", "_IsNonwritableInCurrentImage", "_pei386_runtime_relocator", "_gnu_exception_handler", "_lock_file", "_unlock_file", "_test_and_set", "_call_via_r0", "_call_via_r1", "_call_via_r2", "_call_via_r3", "_call_via_r4", "_call_via_r5", "_call_via_r6", "_call_via_r7", "_call_via_r8", "_call_via_r9", "_call_via_sl", "_call_via_fp", "_call_via_ip", "_call_via_sp", "_call_via_lr",
))
# fmt: on
